JJ/IV-2015-16

.gitignore

Ya he forkeado y creado mi .gitignore, además del fichero objetivos.

forkeado y creado .gitignore

---

objetivos/alejandro-casado.md

Se ha creado el fichero de objetivos llamado alejandro-casado.md

Creación objetivos

---

objetivos/JesusPrietoLopez.md

Pull Request para subir la lista de objetivos de Jesús Prieto López.

Subiendo por primera vez los objetivos

---

objetivos/JavierPerezGarcia.md

Primera semana

---

objetivos/alejandro-casado.md

Ha habido un error en los objetivos, por lo que este pull lo corrige

Corrección de objetivos

---

objetivos/gabriel-stan.md

Primer push de los objetivos semanales

Objetivos de la primera semana

---

objetivos.md

No sé si es lo correcto. He añadido una rama en mi fork y el archivo de mis objetivos a Markdown.

añadida rama y archivo objetivos.md

---

objetivos/Santiago de Diego.md

He añadido mi fichero con los objetivos de la primera semana.

Añadido mi archivo de objetivos

---

objetivos/JoseFranciscoGuerrero.md

Actualización Objetivos

---

objetivos/AlvaroFernandez-Alonso.md

IV Objetivo1

---

objetivos/RosaOrtegaRomero.md

Objetivos s1

---

ejercicios/AlvaroMartinezCampos/tema1/ejercicio1.md
ejercicios/AlvaroMartinezCampos/tema1/ejercicios2.md

Ejercicos1

---

ejercicios/GabrielStan/tema1.md

Subiendo ejercicio 1 del tema 1 y aprendiendo markdown y git

Ejercicio 1 tema 1

---

ejercicios/JavierPerezGarcia/Ejercicios Tema 1.md

He creado el archivo en el que irán los ejercicios del tema 1 y dentro he metido el ejercicio 1

Archivo de ejercicios con el ejercicio 1 dentro

---

ejercicios/JavierPerezGarcia/Ejercicios Tema 1.md

Del ejercicio 2 y 3 tengo ciertas dudas que estoy tratando de resolver, de modo que por eso he subido el 4 después del 1, finalmente estarán en orden

Añadido ejercicio 4

---

objetivos/alejandro-casado.md

Han sido añadidos los objetivos de la segunda sesión

Añadidos objetivos sesión 2

---

ejercicios/JavierPerezGarcia/Ejercicios Tema 1.md

Hay 3 commits porque he intentado que las fotos se vean de forma directa, pero no lo he conseguido, realmente es como si solo hubiera 1

Ejercicios

---

ejercicios/JavierPerezGarcia/Ejercicios Tema 1.md

Arreglado el formato de las listas de gastos durante 4 y 7 años.

Formato correcto en lista de gastos

---

practicas/1.md

Subo link de mi proyecto en GiHub.

Proyecto Chef

---

ejercicios/Alberto Romero/Tema1.md
objetivos/AlbertoRomero.md

Intento de arreglo de conflictos v3

Arreglando conflictos

---

objetivos/BogdanAlinMuresan.md

anadido los objetivos

---

ejercicios/JavierRuizCesar/Tema1.md
objetivos/JavierRuizCesar.md

Resolviendo los conflictos Javier Ruiz Cesar

Resolviendo conflictos

---

objetivos/ObjetivosAlejandroReyesPortellano.md

JuanBorjaAlvarezPeralta.md

---

ejercicios/AlvaroMaximinoLinaresHerrera/Tema1/Tema1.md
objetivos/AlvaroMaximinoLinaresHerrera
objetivos/AlvaroMaximinoLinaresHerrera.md

Subida y actualización de las sesiones y de los ejercicios del tema 1.

Subidas de archivos

---

ejercicios/GabrielStan/tema1.md
objetivos/gabriel-stan.md

Cuidado con los closed issues, @JJ !!

Ejercicios y objetivos tema 1

---

objetivos/AlvaroMartinez.md

objetivos sesion 2

---

ejercicios/AlejandroReyesPortellano/Tema1-EJercicios.md

ejercicios 

---

practicas/1.md

Faltan todavía los detalles del proyecto de DAI, cuando los sepamos actualizo el repositorio.

Añadido el hito de mi proyecto

---

objetivos/SamuelCarmonaSoria.md

Objetivos primera y segunda sesión.

Añadiendo objetivos

---

objetivos/alejandro-casado.md

Se han actualizado los objetivos de la sesión 2

Actualización objetivos sesión 2

---

practicas/1.md

Añadido el enlace del proyecto.

Entrega de la práctica 1

---

practicas/1.md

Alcanzando hito 1
Al parecer estamos todos haciendo pull request al mismo archivo y segun se va aceptando uno da conflicto a los siguientes

Resolviendo conficto

---

practicas/1.md

Se ha creado el repositorio
Se ha creado el archivo readme.md con la descripción del proyecto
Se ha creado la pagina web del proyecto con pages github, el enlace es: http://ignaciorecuerda.github.io/IV_OpenOrder/

actualización práctica 1

---

practicas/1.md

Enlace al README.md del repositorio de mi proyecto.

Proyecto de la asignatura

---

objetivos/JavierRuizCesar.md

Actualizando objetivos

---

practicas/1.md

Actualización con mi proyecto

---

ejercicios/AndresSerranoGomez/1.md

Arreglados los errores de cálculo del IVA

Arreglar errores

---

ejercicios/SamuelCarmonaSoria/EjerciciosTema1.md

Ejercicios actualizados Tema 1

Actualizados ejercicios Tema 1

---

practicas/1.md

Hito 1 de nuevo

---

objetivos/MiguelAngelGarciaVillegas.md

Vuelvo a subir los Objetivos 1

---

objetivos/AlvaroFernandez-Alonso.md

Actualizados objetivos sesion 2

---

practicas/1.md

corrigiendo error

---

ejercicios/MiguelAngelGarciaVillegas/EjerTema1.md
objetivos/MiguelAngelGarciaVillegas.md

Carpeta y Objetivos

---

ejercicios/AlvaroAraluce/Tema1.md

Ejercicio 3

---

practicas/1.md

Actualizando la práctica 1

---

ejercicios/AlvaroMaximinoLinaresHerrera/Tema1/Tema1.md

Se ha subido la solución al ejercicio 2, de forma que ya se cumple el 80% para que se tenga en cuenta el primer hito.

Actualización ejercicios.

---

ejercicios/MiguelAngelGarciaVillegas/EjerTema1.md

Ejercicios Tema 1

---

practicas/1.md

Si algo no estuviera bien por favor comuniquemelo lo antes posible. gracias

Entrega del primer hito arreglado

---

ejercicios/MiguelAngelGarciaVillegas/EjerTema2.md
objetivos/MiguelAngelGarciaVillegas.md

Nuevos Objetivos a partir del 14 y Hito 2

---

practicas/1.md

Añadiendo enlace subrepositorio propio.

Añadiendo enlace subrepositorio propio

---

practicas/1.md

- Corrección de la descripción de herramientas del proyecto.
- Añadida inscripción al certamen de Proyectos Libres de la UGR.
- Modificación del enlace al repositorio del proyecto(cambio nombre repositorio).

Modificaciones proyecto

---

practicas/1.md

El proyecto se presentó el 19 de octubre, modifico el archivo para notificarlo

Proyecto presentado al certamen de software libre

---

objetivos/SalvadorRueda.md

Objetivos semana 2 actualizados.

objetivos añadidos

---

practicas/1.md

Unicamente he añadido el texto "Revisar" para indicar que esta corregido el repositorio. Ya estaba corregido antes del miércoles, únicamente lo pongo para que no quede duda

actualizado repositorio Jose Ignacio Recuerda

---

practicas/1.md

Modificado enlace al repo

---

ejercicios/DavidSantiagoCarrion/tema1.md
ejercicios/DavidSantiagoCarrion/tema2.md
objetivos/DavidSantiagoCarrion.md
practicas/1.md

Acabo de ver el correo. Siento haber modificado el archivo de prácticas sin haber subido antes los ejercicios y objetivos. Ha sido un malentendido, creí que estaba en otro repositorio.
Ahora si adjunto ejercicios y objetivos.

Ejercicios y objetivos

---

ejercicios/SantiagoDeDiego/Ejercicios tema 2.md
objetivos/Santiago de Diego.md

Ejercicio 6 terminado y sustituída la aplicación de prueba por una que permite pasar tests

Ejercicio 6

---

ejercicios/RafaelLachicaGarrido/Tema3_NUEVO_RafaelLachicaGarrido.md

Corrección del tema 3, del nuevo enunciado de ejercicios. Desplegando app en Heroku

Ejercicios Tema 3 Nuevos

---

ejercicios/JavierRuizCesar/Tema2.md
practicas/1.md

Actualizando el enlace de la practica uno y ejercicios del tema 2

Actualizando el enlace de la practica 1

---

ejercicios/AlvaroAraluce/Tema2.md

Ejercicio 2 Tema 2

---

practicas/2.md

Hola Francisco Neveros, llevo con el mismo problema desde ayer, no he modificado la linea de mi compañero Alejandro Casado pero aun así aparece como modificada en el pull request. JJ me ha dicho que puede ser devido a una diferencia horaria en algun merge y que lo deje indicado, no obtante, mañana me pasare por su turno de practicas para que vea usted mismo vea lo que hago. 
Un saludo y perdón por las molestias

hito 2 de practicas

---

objetivos/JesusPrietoLopez.md

Me faltaban los objetivos del tema 2

Subiendo los objetivos del tema 2

---

ejercicios/AlvaroAraluce/Tema2.md

Ponemos captura de travis

---

practicas/1.md

Hemos tenido que cambiar el proyecto porque uno de nuestros compañeros se ha dado de baja en la asignatura. Hablamos con @JJ y nos dijo que podíamos hacer el cambio.
Un saludo

Redirigiendo al nuevo repo

---

ejercicios/AlejandroReyesPortellano/Tema2-Ejercicios.md
practicas/1.md

Hemos tenido que cambiar el proyecto porque uno de nuestros compañeros se ha dado de baja en la asignatura. Hablamos con @JJ y nos dijo que podíamos hacerlo. Un saludo

actualizando enlace

---

ejercicios/JavierRuizCesar/Tema2.md

ejercicios del tema 2 terminados

acabando ejercicios tema 2 

---

practicas/2.md

Vamos al hito 2

---

practicas/2.md

Me he colocado en la línea de mi compañero

Poniendome en mi propia linea

---

objetivos/JoseIgnacioRecuerdaCambil.md

Perdón, en las prácticas pone: Haber alcanzado el 80% de los objetivos del tema introductorio tras haber realizado los ejercicios propuestos. y el enlace que lleva esa frase son a los ejercicios del tema 2, y estos objetivos los tenia superados. Acabo de actualizar los objetivos del tema siguiente que ya había superado, creo que pasan con creces el 80% de los objetivos

 actualizados los objetivos cubiertos del tema 4

---

ejercicios/AlvaroPerez/Tema2.md

Añado un ejericcio más para cumplir con el 80%.

Añadiendo ejercicio 7

---

practicas/2.md

Lo entregué a tiempo, auqnue con un retorno de carro en la línea de un compañero por error.

Añadida revisión

---

objetivos/RubenMartin.md
sesiones/6-semana.md

He corregido el nombre del tema que estamos haciendo, que es sobre PaaS y no contenedores. Y si hemos empezado contenedores pues será el enlace lo que está mal.

cambio en sesion semana 6

---

practicas/2.md

Actualizando los fallos del hito 2

Actualizando el hito 2

---

practicas/2.md

Añadido Hito 2 - REVISAR 1

---

ejercicios/MiguelAngelGarciaVillegas/EjerTema2 ProyectoInsertaLogo.md
ejercicios/MiguelAngelGarciaVillegas/EjerTema2.md
objetivos/MiguelAngelGarciaVillegas.md
practicas/2.md

Nuevo Upstream Hito 2 Revisar1 

---

ejercicios/MiguelAngelGarciaVillegas/EjerTema2 ProyectoInsertaLogo.md

Ya he encontrado el problema. 
El fichero travis en el repositorio github tiene que llamarse .travis.yml

Fichero en el Repositorio .travis.yml

---

ejercicios/SantiagoDeDiego/Ejercicios tema 3.md
objetivos/Santiago de Diego.md
practicas/3.md

Añadidos ejercicios y enlace al README del proyecto donde aparece la explicación de su despliegue, así como el enlace al sitio web

Despliegue del proyecto y avanzo ejercicios

---

ejercicios/AntonioPozo/Tema3.md
practicas/2.md

COMENTARIOS DE LA REVISIÓN 1: “Gruntfile no ejecuta los tests, incluyes ficheros innecesarios, no enlazas el Travis.”
Para ejecutar los test utilizo el makefile no el gruntfile. 
Limpiados los archivos que no son necesarios. 
El repositorio estaba enlazado a Travis. Me has hecho esa observación supongo por que no estaba la etiqueta arriba en el repositorio. Ya está puesta.
Saludos

Revisar 2 AntonioPozo

---

ejercicios/JavierPerezGarcia/Ejercicios Tema 3.md

Me falta por hacer 1, el resto están hechos

Añadiendo ejercicios del tema 3

---

ejercicios/SantiagoDeDiego/Ejercicios tema 2.md

He añadido un tutorial a mis ejercicios del tema 2 que habla sobre las distintas versiones de python y como crear entornos virtuales para ambas de forma cómoda. Puede resultar útil a mi me costó bastante entender el sistema

Añadido un tutorial

---

practicas/2.md

Revisión 2 Hito 2

---

ejercicios/PabloMartin-MorenoRuiz/Tema3.md

Subo algunos ya para comprobar que no me va mal github a última hora. Cómo siemore...

Subiendo algunos ejercicios del tema 3

---

practicas/3.md

No hice nada desde ayer en las entregas, (ni práctica ni ejercicios ni objetivos), pero se me olvidó poner el enlace en el fichero md de entrega de prácticas.

Enlace entrega p3

---

ejercicios/PabloMartin-MorenoRuiz/Tema2.md

Como en el Tema 3 se me estropeo el repositorio de CalificacionesEmpresas, lo he cambiado por el nuevo. Solo ha sido cambiar enlaces

modificando ejercicios tema 2

---

practicas/4.md

Añadido el archivo 4.md para la cuarta entrega y añadido mi enlace. Aún falta crear un repositorio en DockerHub con el contenedor del proyecto, pero eso no me ha salido todavía.

Añadido enlace al cuarto hito

---

ejercicios/AlvaroAraluce/Tema3.md
objetivos/AlvaroFernandez-Alonso.md

Retomando IV - 60% Tema3

---

ejercicios/JesusPrietoLopez/Tema4.md
objetivos/JesusPrietoLopez.md
practicas/4.md

Pull request con los ejercicios del tema 4, los objetivos de las últimas semanas y el enlace a la práctica con el 4 hito realizado.

Jplcommits

---

ejercicios/AngelValera/tema4.md
objetivos/AngelValeraMotos.md
practicas/4.md

Subo el hito 4 aunque es un día después, ¿tengo que indicarlo en mi línea del fichero, o no hace falta?

Subiendo hito 4, ejercicios tema 4 y objetivos 

---

ejercicios/SamuelCarmonaSoria/EjerciciosTema4.md

Arreglando link de docker, sobraba una "/" al final.

Fixing docker link

---

ejercicios/RafaelLachicaGarrido/Tema5.md
objetivos/RafaelLachicaGarrido_obj1.md

Solo falta acabar el Juju, pero se me está agotando la RAM entre tanta máquina virtual y guardo por si acaso esto peta y tengo que reiniciar.

Ejercicios Tema 5

---

practicas/4.md

Añadido despliegue automático con fabric y avanzado un poco el proyecto

Solicitud de primera revisión del hito 4

---

ejercicios/SamuelCarmonaSoria/ejerciciosTema5.md

Añadiendo ejercicios tema 5

---

ejercicios/AntonioPozo/Tema6.md
practicas/5.md

Es un repo diferente al de las anteriores entregas.

Añado repositorio de la entrega

---

practicas/5.md

para que sea más facil de acceder. tambien esta en el badge de despliegue del README del repo

Añadido enlace al despliegue

---

ejercicios/AntonioPozo/Tema6.md

Ejercicio 8 terminado

---

ejercicios/JavierPerezGarcia/Ejercicios Tema 6.md

Haciendo repaso de la asignatura me he dado cuenta de que tenía este ejercicio hecho, pero no entregado, perdón por la tardanza. Creo que ya cumplía el mínimo, pero bueno, ya que lo tengo hecho, que quede constancia.

Redactando un ejercicio que tenía hecho
